/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import domain.Korisnik;
import domain.Poruka;
import java.util.List;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import komunikacija.Odgovor;
import komunikacija.Operacije;
import komunikacija.Zahtev;
import nit.NitZaCitanje;

/**
 *
 * @author Rusimovic
 */
public class GlavnaForma extends javax.swing.JFrame {

    Korisnik korisnik;
    NitZaCitanje nitZaCitanje;
    Komunikacija komunikacija;
    private List<Korisnik> sviKorisnici;

    GlavnaForma(Komunikacija komunikacija, Korisnik korisnik, NitZaCitanje nitZaCitanje) {
        initComponents();
        TableModelPoruke poslednje3 = new TableModelPoruke();
        TableModelPoruke svePoruke = new TableModelPoruke();
        TableModelPoruke porukeOdredjenogKorisnika=new TableModelPoruke();
        porukeOdredjenogKorisnika.setPorukeZaPrikaz(porukeOdredjenogKorisnika.getSvePoruke());
        svePoruke.setPorukeZaPrikaz(svePoruke.getSvePoruke());
        poslednje3.setPorukeZaPrikaz(svePoruke.getPoslednje3poruke());
        
        this.korisnik = korisnik;
        this.komunikacija = komunikacija;
        this.nitZaCitanje = nitZaCitanje;
        tblPoslednje3poruke.setModel(poslednje3);
        tblSvePoruke.setModel(svePoruke);
        tblPorukeKorisnika.setModel(porukeOdredjenogKorisnika);
        cmbSviKorisnici.removeAllItems();
        cmbPrijavljeniKorisnici.removeAllItems();
        postaviKorisnika();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSifra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPorukaSvima = new javax.swing.JTextField();
        btnPosaljiSvima = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbPrijavljeniKorisnici = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtPorukaSvima1 = new javax.swing.JTextField();
        btnPosaljiPorukuSvima1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoslednje3poruke = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSvePoruke = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnCelaPoslednjeTri = new javax.swing.JButton();
        btnCelaSve = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbSviKorisnici = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPorukeKorisnika = new javax.swing.JTable();
        btnPorukeOdKorisnika = new javax.swing.JButton();
        btnPrikaziCitavuPoruku = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email:");

        jLabel2.setText("Sifra:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Slanje poruka"));
        jPanel1.setName(""); // NOI18N

        jLabel3.setText("Tekst poruke:");

        btnPosaljiSvima.setText("Posalji svima");
        btnPosaljiSvima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiSvimaActionPerformed(evt);
            }
        });

        jLabel6.setText("Posalji poruku odredjenom korisniku");

        cmbPrijavljeniKorisnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Tekst poruke:");

        btnPosaljiPorukuSvima1.setText("Posalji");
        btnPosaljiPorukuSvima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiPorukuSvima1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPorukaSvima, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPosaljiSvima))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(cmbPrijavljeniKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(txtPorukaSvima1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPosaljiPorukuSvima1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPorukaSvima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPosaljiSvima)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPrijavljeniKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPorukaSvima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPosaljiPorukuSvima1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Prijem poruka"));

        tblPoslednje3poruke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPoslednje3poruke);

        jLabel4.setText("Poslednje tri poruke");

        tblSvePoruke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSvePoruke);

        jLabel5.setText("Sve poruke");

        btnCelaPoslednjeTri.setText("Cela poruka");
        btnCelaPoslednjeTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelaPoslednjeTriActionPerformed(evt);
            }
        });

        btnCelaSve.setText("Cela poruka");
        btnCelaSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelaSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(175, 175, 175)
                        .addComponent(btnCelaPoslednjeTri))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCelaSve))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCelaPoslednjeTri)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCelaSve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbSviKorisnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSviKorisnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSviKorisniciActionPerformed(evt);
            }
        });

        tblPorukeKorisnika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblPorukeKorisnika);

        btnPorukeOdKorisnika.setText("Prikazi poruke od korisnika");
        btnPorukeOdKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorukeOdKorisnikaActionPerformed(evt);
            }
        });

        btnPrikaziCitavuPoruku.setText("Prikazi citavu poruku");
        btnPrikaziCitavuPoruku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziCitavuPorukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(279, 279, 279)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 104, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnPorukeOdKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(cmbSviKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrikaziCitavuPoruku, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPorukeOdKorisnika)
                    .addComponent(cmbSviKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziCitavuPoruku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        komunikacija.prekiniKomunikaciju();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCelaPoslednjeTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelaPoslednjeTriActionPerformed
        if (tblPoslednje3poruke.getSelectedRow() != -1) {
            Poruka poruka = ((TableModelPoruke) tblPoslednje3poruke.getModel()).getPoruka(tblPoslednje3poruke.getSelectedRow());
            JOptionPane.showMessageDialog(this, poruka.getPoruka());
        } else {
            return;
        }

    }//GEN-LAST:event_btnCelaPoslednjeTriActionPerformed

    private void btnCelaSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelaSveActionPerformed
        if (tblSvePoruke.getSelectedRow() != -1) {
            Poruka poruka = ((TableModelPoruke) tblSvePoruke.getModel()).getPoruka(tblSvePoruke.getSelectedRow());
            JOptionPane.showMessageDialog(this, poruka.getPoruka());
        } else
            return;
    }//GEN-LAST:event_btnCelaSveActionPerformed

    private void btnPorukeOdKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorukeOdKorisnikaActionPerformed
        prikaziPorukeOdOdredjenogKorisnika();

    }//GEN-LAST:event_btnPorukeOdKorisnikaActionPerformed

    private void btnPrikaziCitavuPorukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziCitavuPorukuActionPerformed
        if(tblPorukeKorisnika.getSelectedRow()!=-1){
            Poruka poruka= ((TableModelPoruke) tblPorukeKorisnika.getModel()).getPoruka(tblPorukeKorisnika.getSelectedRow());
            JOptionPane.showMessageDialog(this, poruka.getPoruka());
        }
        else return;
    }//GEN-LAST:event_btnPrikaziCitavuPorukuActionPerformed

    private void cmbSviKorisniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSviKorisniciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSviKorisniciActionPerformed

    private void btnPosaljiSvimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiSvimaActionPerformed
        String txtPoruke = txtPorukaSvima.getText().trim();
        if (txtPoruke.length() > 200) {
            JOptionPane.showMessageDialog(this, "Poruka ne sme biti duza od 200 karaktera!");
            return;
        }

        if (!txtPoruke.isEmpty()) {
            Zahtev zahtev = new Zahtev();
            Poruka poruka = new Poruka();
            poruka.setPoruka(txtPoruke);
            poruka.setOdKorisnika(korisnik);
            poruka.setVreme(LocalDateTime.now());
            zahtev.setOperacija(Operacije.SLANJE_OPSTE_PORUKE);
            zahtev.putData("poruka", poruka);
            try {
                komunikacija.posalji(zahtev);
            } catch (IOException ex) {
                Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPosaljiSvimaActionPerformed

    private void btnPosaljiPorukuSvima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiPorukuSvima1ActionPerformed
        String txtPoruke = txtPorukaSvima1.getText().trim();
        if (txtPoruke.length() > 200) {
            JOptionPane.showMessageDialog(this, "Poruka ne sme biti duza od 200 karaktera!");
            return;
        }
        Korisnik odKorisnika = this.korisnik;
        Korisnik kaKorisniku = (Korisnik) cmbPrijavljeniKorisnici.getSelectedItem();
        System.out.println(kaKorisniku.getEmail());
        Poruka poruka=new Poruka();
        poruka.setKaKorisniku(kaKorisniku);
        poruka.setOdKorisnika(odKorisnika);
        poruka.setPoruka(txtPoruke);
        poruka.setVreme(LocalDateTime.now());
        Zahtev zahtev = new Zahtev();
        zahtev.setOperacija(Operacije.SLANJE_PORUKA_ODREDJENOM_KORISNIKU);
        zahtev.putData("poruka", poruka);
        try {
            komunikacija.posalji(zahtev);
        } catch (IOException ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPosaljiPorukuSvima1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void postaviKorisnika() {
        txtEmail.setText(korisnik.getEmail());
        txtSifra.setText(korisnik.getSifra());
    }
    
    public void dodajKorisnika(Korisnik korisnik) {
        sviKorisnici.add(korisnik);
        cmbPrijavljeniKorisnici.removeAllItems();
        for (Korisnik k : sviKorisnici) {
            cmbPrijavljeniKorisnici.addItem(k);
        }

    }
    
     public void azurirajKorisnike(Odgovor odgovor) {
        List<Korisnik> korisnici = (List<Korisnik>) odgovor.getData("korisnici");
        cmbPrijavljeniKorisnici.removeAllItems();
        cmbSviKorisnici.removeAllItems();
        for (Korisnik k : korisnici) {

            cmbPrijavljeniKorisnici.addItem(k);
            cmbSviKorisnici.addItem(k);
        }
        cmbPrijavljeniKorisnici.removeAllItems();
        for (Korisnik k : korisnici) {
            cmbPrijavljeniKorisnici.addItem(k);
        }
    }
    
     private void prikaziPorukeOdOdredjenogKorisnika() {
        Korisnik korisnik=(Korisnik) cmbSviKorisnici.getSelectedItem();
        List<Poruka> porukeKorisnika = new ArrayList<>();
        for(Poruka p:((TableModelPoruke) tblPoslednje3poruke.getModel()).getSvePoruke()){
            if(p.getOdKorisnika().equals(korisnik)) porukeKorisnika.add(p);
            
        }
 
        ((TableModelPoruke) tblPorukeKorisnika.getModel()).setPorukeZaPrikaz(porukeKorisnika);
        ((TableModelPoruke) tblPorukeKorisnika.getModel()).fireTableDataChanged();
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCelaPoslednjeTri;
    private javax.swing.JButton btnCelaSve;
    private javax.swing.JButton btnPorukeOdKorisnika;
    private javax.swing.JButton btnPosaljiPorukuSvima1;
    private javax.swing.JButton btnPosaljiSvima;
    private javax.swing.JToggleButton btnPrikaziCitavuPoruku;
    private javax.swing.JComboBox cmbPrijavljeniKorisnici;
    private javax.swing.JComboBox cmbSviKorisnici;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblPorukeKorisnika;
    private javax.swing.JTable tblPoslednje3poruke;
    private javax.swing.JTable tblSvePoruke;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPorukaSvima;
    private javax.swing.JTextField txtPorukaSvima1;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables

    public void azurirajPoruke(Odgovor odgovor) {
        ((TableModelPoruke) tblPoslednje3poruke.getModel()).addPoruka((Poruka) odgovor.getData("poruka"));
        ((TableModelPoruke) tblSvePoruke.getModel()).addPoruka((Poruka) odgovor.getData("poruka"));
        

    }
    
    
}
